include: package:analysis_defaults/flutter.yaml
# analyzer:
#   exclude: [build/**]
#   language:
#     strict-casts: true
#     strict-raw-types: true
#   strong-mode:
#     implicit-casts: false
# linter:
#   rules:
#     - cancel_subscriptions